[tool.poetry]
name = "dragon-cli"
version = "0.0.1"
description = ""
authors = ["straydragon <straydragonl@foxmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
click = "^7.0"
munch = "^2.5.0"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
pytest-mock = "^1.13.0"
pytest-cov = "^2.8.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
