name="neovim"

[config]
comment="$man nvim"

[[config.lookup_paths]]
order = 1
path = "~/.config/nvim/init.vim"
need_auth = false
default_hit = true

[[config.lookup_paths]]
order = 2
path = "~/.config/nvim"
need_auth = false
default_hit = false

[[config.lookup_paths]]
order = 3
path = "$VIM/sysinit.vim"
need_auth = true
default_hit = false


[[config.lookup_paths]]
order = 4
path = "/usr/local/share/nvim"
need_auth = true
default_hit = false
