name="zsh"

[config]
comment="$man zsh"

[[config.lookup_paths]]
order = 1
path = "~/.zshrc"
need_auth = false
default_hit = true

[[config.lookup_paths]]
order = 2
path = "/etc/.zshrc"
need_auth = true
default_hit = false
