name="i3status"

[config.linux]
comment="$man i3status"

[[config.linux.paths]]
order = 1
path = "~/.config/i3status/config"
need_auth = false

[[config.linux.paths]]
order = 2
path = "/etc/xdg/i3status/config"
need_auth = true

[[config.linux.paths]]
order = 3
path = "~/.i3status.conf"
need_auth = false

[[config.linux.paths]]
order = 4
path = "/etc/i3status.conf"
need_auth = true

