name="proxychains"

[config.linux]
comment="https://github.com/rofl0r/proxychains-ng"

[[config.linux.paths]]
order = 1
path = "./proxychains.conf"
need_auth = false

[[config.linux.paths]]
order = 2
path = "~/.proxychains/proxychains.conf"
need_auth = false

[[config.linux.paths]]
order = 3
path = "/etc/proxychains.conf"
need_auth = true
