name="ranger"

[config.linux]
comment="$man ranger"

[[config.linux.paths]]
order = 1
path = "~/.config/ranger"
need_auth = false

[[config.linux.paths]]
order = 2
path = "$XDG_CONFIG_HOME/ranger"
need_auth = false
if_set = "$XDG_CONFIG_HOME"
